import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import './line-awesome.css'
import "rc-slider/assets/index.css";
import Provider from "@/app/redux/provider";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
